language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: AstroHackWeek/hacks-collector
        branch: master

env:
    global:
        - secure: "qGl7jlTdPwmp7oJHv/0/ejefWf/qZO78Rt1L9VLFPP/At6/bQGWm/dZPmIbeLiWIXdF7xSGlmDhCxg6jto4oYCu0Dyb74UXbU4h63yeRdw/BTAixyXxpSdvPvHSYi381qXE/m0tznIsYdVlPVwhu+b2je0Zebh+bGK2zW4rdInd2lWYORj0lLAOZtcFHduiJdDhOUrdTeW+jOWUe8f9fXRMNHdJb3xMsNF+19QVVJymhIPaTmU4dgE1Tp2U3dSQHFKTZyIoLoFUezFisUCekdioVzrU/l3X4SbY83cnF5Xpc3fpguH2nUUUUWxXJLGrL4BFop3ccKuBIxp8HeKHtyD1Yvghia6nNQQPy6oBPmIF6U9T/qjTk9dHvE3kFPAdXtXt0vOX78e1eNTkKToknnAlbFA/kL5Rxll0bGfmEDciKJkW5vs/Jv4ElxgjdyOb5anqIdeQVRtqeQ5ByAAC85WFTL4du6dr08sTsNEQyYpa/nlavVo55nu14eoaKhJtjLOstWttubEUkDBrLFJmhBxOYz48e8sducqcMsM48VEw1jDeEuCFCx2ZB2OGGVKyL7ZZRyiD+VeIgYUUesWnXGbXHDe9B39lawI8mkO6ijOQHFtaMntuwxTESPQBLP/3fyYjmVNZH2Uez9KQL8gIKfhcC23LwhdL1OsGJezD6lFw="
