language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: AstroHackWeek/hacks-collector
        branch: master

env:
    global:
        - secure: "UuvM42a/KC/HtLuBfw6SV9UwgOnqhSDp3cF6VLyk41Ae+hPzPx5dnQfAjQnLvVUhLihi5jL3YwFx7QUPSsJOTKhIVAmr5TIeEw/lQLTgLK9xrAzAu5xuORp3jdg1T3jFn3BMVbHPuC90R4wwLe+9uSoNRRVDuWHTajLzuJqzim9L8/PU3Q4xFf3Xx+taMS8XPtUbQYg/g/bXffXPCbbwCsgBJ4tZw62UCyH1nNDXXbrFUdgS1AuvGVZcr3Yh16ozRILETTiB4x14cE3Q0uR6l5h9XdBVIDMwEW7BMdwE70oGyj8t82qoVbDOuJh/pksaHvfIzEhConeLALH7B7vaTSOqcLn13rEDRCs+0q8psXbJmictOl0IRfVAH/BhUbCPxqhGh8m/enEelOG41XHqC9IdQdEyEqk9cIwxR5i63NYtA57eGm+mrjqp4jRLlIoffQh6FME5JsYzBofu6DQ2/5GVVgtw2TWxkWSHusFNS3vJ3K7xo3MAV1D/6SlMU/feTc2CsHLpN7tvHSkLyH6GR8gf/v48kbjU3YTj0RgxVjOtz8LTLndJh1Duc5fxZurfQX4jGeOlSOi2zOhn2I0J091VH6WQgZsOBvAGtX7ogCst41fZpiRpzi0LrOZn55Voz1Zf5v7FRNXchws2rZ2Ng11tYKJs4X2M6naVl7ntTkE="
